title: Tardes ao vento
author:
  name: GitHub User
  email: your-email@domain.com
description:  # this means to ignore newlines until "show_excerpts:"

# URL settings
url: "https://blog.tardesaovento.com.br" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

minima:
  skin: tardesaovento
  date_format: "%b %-d, %Y"
